# Use root/example as user/password credentials
version: "3.7"

services:
    ateliware-amazonia:
        image: ateliware-amazonia
        container_name: Ateliware-amazonia
        environment:
            - ASPNETCORE_ENVIRONMENT
        ports:
            - 80:80